config/routes.rb
Rails.application.routes.draw do
  root "pages#home" #creates home page
  get "about" => "pages#about" #creates about path
  get "blog" => "pages#blog"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end

  def blog
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Pinteresting</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to 'Home', root_path %> </li>
        <li><%=link_to 'About Me', about_path %> </li>
        <li><%=link_to 'Blog', blog_path %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>
	
</body>
</html>

app/views/pages/about.html.erb
<div class='jumbotron'>
<h2>About Me</h2>
<p> My name is Mike Cerrrone and I am a first time web developer excited to recreate one of the internets most popular applications, PINTEREST. I actually have never used Pinterest and thought that it would be the perfect first project! Hold on to your hats because there's going to be a lot of learning going on! </p>

app/views/pages/blog.html.erb
<div class='jumbotron'>
<h2>Blog</h2>
<p> Hello world! How exciting!! </p>

app/views/pages/home.html.erb
<div class='jumbotron center'>
	<h1>Welcome To My Carrot App!</h1>
	<p><%= link_to "Log in", "#", class: "btn btn-default btn-lg" %> <%= link_to "Sign Up", "#", class: "btn btn-primary btn-lg" %></p>